### ISSUE TITLE
Implement an inventory system

### ISSUE THREAD

**Issue by mattwwarren** [mattwwarren/twubot#29]
From reddit: 

> I am streaming Pokemon and me and my mods have come up with an Elite 4 challenge. The only reason why it's not working at this point in time is because we wanted players to have the ability to buy revives for their team. So basically you type in a command which then sends a message to my bot telling it to take earned credits from their total balance. In exchange they for example get 1 revive which they can spend by using another command.

So from this, mod commands to manage the "shop" inventory (should items be limited? Optionally?) and all access to buy from the shop

**Comment by mattwwarren** [comment]
Also, should inventory be limited? Number of items you can hold overall or number of a single item that can be held at one time?

**Comment by Red040** [comment]
Hey, great initiative! Subbed so I can keep progress!

Limited inventory would nice. Maybe a viewer could have a total of for example 5 different items that can be stacked up to 10 of each? Perhaps a command like !discard 'item' to get rid of items they no longer need?

**Comment by mattwwarren** [comment]
The functionality has been added as requested. Available commands are:

!addinventory {item} {cost} {defaultStock}
!addstock {item} {number}
!purchase {item}
!sell {item} [{count}]
!discard {item} [{count}]
